# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarriel <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/08/23 12:17:59 by abarriel          #+#    #+#              #
#    Updated: 2016/08/24 20:33:23 by abarriel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_tail
SRCS = ft_tail

all:	$(NAME)

$(NAME) : 
	gcc -Werror -Wall -Wextra ft_tail.c ft.c -o ft_tail
clean : 
	rm -f ft_atoi.o
fclean : 
	rm -f $(NAME)
re : fclean all
