# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abarriel <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/08/23 12:17:59 by abarriel          #+#    #+#              #
#    Updated: 2016/08/24 20:09:25 by abarriel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat
SRCS = ft_cat

all:	$(NAME)

$(NAME) : 
	gcc -Wall -Werror -Wextra ft_cat.c ft.c -o ft_cat
clean : 
	rm -f ft_cat.o
fclean : 
	rm -f $(NAME)
re : fclean all
